### ISSUE TITLE
Invalid Grant Type Error

### ISSUE THREAD

**Issue by ronnycarr** [flochtililoch/homebridge-pivot-power-genius#4]
Hi there, I got access to the Wink API and installed the plugin but when I try to start homebridge i get an authorization error `invalid_grant: This client is not permitted to use the password grant type`. Any advice is much appreciated!

**Comment by flochtililoch** [comment]
Seeing this a bit late, sorry about that - did you configure the plugin with valid `client_id` and `client_secret`?

**Comment by smartymanav** [comment]
I am also seeing the same error and yes I followed the instructions and added both username/password and clientid/secret to the json config

**Comment by flochtililoch** [comment]
This probably has to do with which API version your client has access to. The underlying API client this plugin uses is https://github.com/winfinit/wink-js, which leverage API v1. My guess is your client is for API v2

**Comment by smartymanav** [comment]
Hmm, so how do I work around this?
Thanks!

**Comment by flochtililoch** [comment]
You should email Wink (same contact you used to get your client ID/secret created) and ask them to switch your client to API v1

**Comment by smartymanav** [comment]
they have actually "upgraded" the process of creating an app - its all done
online now, I didn't have to email any one..

**Comment by sibartlett** [comment]
@flochtililoch maybe you should try adding support for API v2?

I've implemented it in [homebridge-wink3](https://github.com/sibartlett/homebridge-wink3), so you can use that as a reference.

**Comment by flochtililoch** [comment]
Thanks - I don't have time to maintain this plugin anymore, but I will gladly review pull requests for such improvements. @sibartlett does you plugin supports the pivot power genius? If so I may as well direct users to use your plugin instead

**Comment by sibartlett** [comment]
No my plugin doesn't support pivot power genius - in fact, I've been directing users to your plugin!

**Comment by LordZork** [comment]
Is this plugin still working for anyone?  If so, please see https://github.com/flochtililoch/homebridge-pivot-power-genius/issues/8 and let me know, thanks!
